language: python
python:
    - "2.7"
    - "3.6"
env:
    - TOX_ENV=metrics
    - TOX_ENV=lint
    - TOX_ENV=coverage
before_install:
  - pip install --upgrade pytest
  - pip install six
install:
    - pip install -r requirements.txt
    - pip install tox
    - pip install coveralls
script:
    - tox -e $TOX_ENV-$TRAVIS_PYTHON_VERSION
after_success:
    - coveralls
